Increase execution count when execution marked for restart
ansible/azure-aap-deployment-driver pull request #40
Opened 2023-03-29 18:56 UTC by tznamena

This PR carries the execution count from stored execution to the new one when execution is marked for restart. This has to be done because the execution starts with a fresh instance.

2023-03-29 18:59 UTC, bhavenst approved these changes
Seems reasonable.  I think it would be better to use the db to count the executions and remove the executioncount field but that is more complicated at this point so we should probably go with this for now..  Did you test it?

2023-03-29 19:01 UTC, tznamena commented
Removing the execution count field from the struct is the next change, but like you said it is bigger change, so that's why I'm proposing this change as quick patch for the issue for now.
Testing it now.

2023-03-29 21:59 UTC, tznamena commented
Did one test and it did increase the count:
```[
    {
        "ID": 5,
        "status": "Restarted",
        "stepId": 5,
        "error": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
        "errorDetails": "Code: Conflict - Message: {\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The 'AzureAsyncOperationWaiting' resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"Conflict\",\r\n            \"message\": \"{\\r\\n  \\\"status\\\": \\\"Failed\\\",\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n    \\\"message\\\": \\\"The 'AzureAsyncOperationWaiting' resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n    \\\"details\\\": [\\r\\n      {\\r\\n        \\\"code\\\": \\\"ReconcileControlPlaneCertificatesError\\\",\\r\\n        \\\"message\\\": \\\"key pool is empty\\\"\\r\\n      }\\r\\n    ]\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}\n",
        "code": "DeploymentFailed",
        "provisioningState": "Failed",
        "details": "",
        "timestamp": "2023-03-29T21:33:10.2560646Z",
        "duration": "48 minutes 29.30 seconds",
        "correlationId": "0c8159f8-592a-4a33-91f5-6ed08c53d87a",
        "executionCount": 1
    },
    {
        "ID": 6,
        "status": "Started",
        "stepId": 5,
        "error": "",
        "errorDetails": "",
        "code": "",
        "provisioningState": "",
        "details": "",
        "timestamp": "0001-01-01T00:00:00Z",
        "duration": "",
        "correlationId": "",
        "executionCount": 2
    }
]

```

2023-03-30 00:02 UTC, bhavenst commented
Cool, go ahead with it.

2023-03-30 15:23 UTC, bhavenst requested changes
Need to update the unit tests..
# server/model_test [server/model.test]
model/model_test.go:73:3: unknown field 'ExecutionCount' in struct literal of type model.Execution
model/model_test.go:80:31: execution.ExecutionCount undefined (type model.Execution has no field or method ExecutionCount)
model/model_test.go:95:31: execution.ExecutionCount undefined (type model.Execution has no field or method ExecutionCount)

2023-03-30 15:25 UTC, tznamena commented
Will rebuild the container and re-test with the latest change.

2023-03-31 13:48 UTC, bhavenst approved these changes

2023-03-31 13:48 UTC, merged